---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: snowtje
# description will be included in the image's metadata
description: Snow Snow is the bestest cat. Meow meow

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - alacritty
      - edk2-ovmf
      - fzf
      - helix
      - jetbrains-mono-fonts
      - kanshi
      - libvirt
      - mako
      - nerd-fonts
      - qemu
      - rofi-wayland
      - samba
      - sddm
      - swaybg
      - swaylock
      - thunar
      - virt-manager
      - waybar
      - wayfire
      - wf-shell
      - wlr-randr
      - wlsunset
      - wofi
    # remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
      remove:
        - app/org.gnome.Calculator/x86_64/stable
        - app/org.gnome.Calendar/x86_64/stable
        - app/org.gnome.Characters/x86_64/stable
        - app/org.gnome.Contacts/x86_64/stable
        - app/org.gnome.Papers/x86_64/stable
        - app/org.gnome.Logs/x86_64/stable
        - app/org.gnome.Loupe/x86_64/stable
        - app/org.gnome.NautilusPreviewer/x86_64/stable
        - app/org.gnome.TextEditor/x86_64/stable
        - app/org.gnome.Weather/x86_64/stable
        - app/org.gnome.baobab/x86_64/stable
        - app/org.gnome.clocks/x86_64/stable
        - app/org.gnome.font-viewer/x86_64/stable
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  #- type: script
    #scripts:
      #- example.sh
            
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
